# https://jade.fyi/blog/pre-commit-exif-safety/
repos:
    - repo: local
      hooks:
          - id: no-spicy-exif
            name: Ban spicy exif data
            description: Ensures that there is no sensitive exif data committed
            language: system
            entry: exiftool -all= --icc_profile:all -tagsfromfile @ -orientation -overwrite_original
            exclude_types: ["svg"]
            types: ["image"]
