baseURL = 'https://iank.org/'
languageCode = 'en-us'
title = 'iank.org'
theme = 'diary'
copyright = "2014-2023 iank.org"


[params]
imageMaxWidth = 600

[[menu.main]]
url = "/about"
name = "About"
weight = 3
